# Generated by Django 5.2.16 on 2026-07-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='The Time Store', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='ean_code',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='EAN code'),
        ),
        migrations.AddField(
            model_name='product',
            name='gst_percent',
            field=models.CharField(choices=[('0', '0%'), ('5', '5%'), ('12', '12%'), ('18', '18%'), ('28', '28%')], default='18', max_length=3, verbose_name='GST %'),
        ),
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='9101', max_length=10, verbose_name='HSN'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Picture'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_qty',
            field=models.PositiveIntegerField(default=1, verbose_name='Min qty'),
        ),
        migrations.AddField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum retail price, in INR', max_digits=12, verbose_name='MRP'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='remark',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_brand',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='tts_model',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='TTS model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Picture URL (fallback)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=12, verbose_name='Selling price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=20, unique=True, verbose_name='Product ID / ref. code'),
        ),
    ]
