# Generated by Django 5.2.10 on 2026-07-31 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_brand_alter_product_brand_subbrand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wrist Watch', 'Wrist Watch'), ('Wall Clocks', 'Wall Clocks'), ('Perfumes', 'Perfumes'), ('Accessories', 'Accessories'), ('Smart Watchs', 'Smart Watchs'), ('Kids', 'Kids')], max_length=30, verbose_name='Category'),
        ),
    ]
