# Generated by Django 5.2.10 on 2026-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tagline',
        ),
        migrations.AddField(
            model_name='product',
            name='case_material',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Case Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='dial_color',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Dial Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='glass_material',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Glass Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='movement',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Movement'),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_color',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Strap Color'),
        ),
        migrations.AddField(
            model_name='product',
            name='strap_material',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Strap Material'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Warranty Period'),
        ),
    ]
