# Generated by Django 5.2.16 on 2026-07-31 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_tagline_product_case_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(blank=True, default='', help_text='e.g. fragrance notes, key highlights', verbose_name='Features'),
        ),
    ]
