# Generated by Django 5.2.16 on 2026-08-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case_size',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Case Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=20, verbose_name='Gender'),
        ),
    ]
