# Generated by Django 5.2.16 on 2026-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_case_size_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Picture 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Picture 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Picture 4'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wrist Watch', 'Wrist Watch'), ('Wall Clocks', 'Wall Clocks'), ('Perfumes', 'Perfumes'), ('Accessories', 'Accessories'), ('Smart Watchs', 'Smart Watchs'), ('Kids Watch', 'Kids Watch')], max_length=30, verbose_name='Category'),
        ),
    ]
