# Generated by Django 5.2.16 on 2026-08-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_image2_product_image3_product_image4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbrand',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sub_brands/'),
        ),
    ]
