# Generated by Django 5.2.16 on 2026-08-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_subbrand_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbrand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='sub_brands/banners/'),
        ),
    ]
