# Generated by Django 5.2.16 on 2026-08-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_subbrand_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subbrand',
            name='banner',
        ),
        migrations.AddField(
            model_name='brand',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners/'),
        ),
    ]
