# Generated by Django 5.2.16 on 2026-08-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_subbrand_banner_brand_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='banner_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='brands/banners/mobile/'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_variants',
            field=models.ManyToManyField(blank=True, to='store.product'),
        ),
    ]
