# Generated by Django 5.2.16 on 2026-08-15 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_brand_banner_mobile_product_color_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_variants',
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=60, verbose_name='Colour Name')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Image 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Image 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Image 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Image 4')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_colors', to='store.product')),
            ],
        ),
    ]
