# Generated by Django 5.2.10 on 2026-09-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_color_variants_productcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='case_size',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='Case Size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Wrist Watch', 'Wrist Watch'), ('Wall Clocks', 'Wall Clocks'), ('Perfumes', 'Perfumes'), ('Accessories', 'Accessories'), ('Smart Watchs', 'Smart Watchs'), ('Kids Watch', 'Kids Watch')], max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='product',
            name='ean_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EAN code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='9101', max_length=20, verbose_name='HSN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Picture URL (fallback)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ref',
            field=models.CharField(max_length=50, unique=True, verbose_name='Product ID / ref. code'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tts_model',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='TTS model'),
        ),
    ]
