# Generated by Django 5.2.10 on 2026-09-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_case_size_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url2',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Picture 2 URL (fallback)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url3',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Picture 3 URL (fallback)'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url4',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Picture 4 URL (fallback)'),
        ),
    ]
